ALTER TYPE "AuditAction" ADD VALUE 'RASTER_INPUT_UPLOADED';
ALTER TYPE "AuditAction" ADD VALUE 'RASTER_RUN_STARTED';
ALTER TYPE "AuditAction" ADD VALUE 'RASTER_CAPACITY_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE 'RASTER_REVIEW_DECISION_CHANGED';
